### ISSUE TITLE
关于数据集制作的label.txt

### ISSUE THREAD

**Issue by Johnson-yue** [chibohe/text_recognition_toolbox#1]
你好， 可以提供一个 label.txt的样例嘛？

readme中的例子没有看懂，是在图片名称后面加中文的嘛？ 来说明哪些是检测图片，哪些是识别图片？

**Comment by chibohe** [comment]
> 你好， 可以提供一个 label.txt的样例嘛？
> 
> readme中的例子没有看懂，是在图片名称后面加中文的嘛？ 来说明哪些是检测图片，哪些是识别图片？

你好，图片名称就是{图片数据集路径}里每张图片的名称，中文是该张图片的标注内容，中间以空格进行分割。

**Comment by Johnson-yue** [comment]
> > 你好， 可以提供一个 label.txt的样例嘛？
> > readme中的例子没有看懂，是在图片名称后面加中文的嘛？ 来说明哪些是检测图片，哪些是识别图片？
> 
> 你好，图片名称就是{图片数据集路径}里每张图片的名称，中文是该张图片的标注内容，中间以空格进行分割。

哦 ， {文件名}+ “ ” +{标注信息}  是吧 ， 好的，我尝试一下

**Comment by chibohe** [comment]
> > > 你好， 可以提供一个 label.txt的样例嘛？
> > > readme中的例子没有看懂，是在图片名称后面加中文的嘛？ 来说明哪些是检测图片，哪些是识别图片？
> > 
> > 
> > 你好，图片名称就是{图片数据集路径}里每张图片的名称，中文是该张图片的标注内容，中间以空格进行分割。
> 
> 哦 ， {文件名}+ “ ” +{标注信息} 是吧 ， 好的，我尝试一下

是的，有什么问题请及时反馈
