### ISSUE TITLE
variable ‘one_hot' in DAN model is not useful ?? 

### ISSUE THREAD

**Issue by Johnson-yue** [chibohe/text_recognition_toolbox#10]
https://github.com/chibohe/text_recognition_toolbox/blob/5ef1261ec436ee564eb977dcad84ca60b19eaa93/networks/DAN.py#L301

**Comment by chibohe** [comment]
> https://github.com/chibohe/text_recognition_toolbox/blob/5ef1261ec436ee564eb977dcad84ca60b19eaa93/networks/DAN.py#L301

The predict script for DAN has been implemented, please try again.
