### ISSUE TITLE
请问SAR如何进行训练呢？

### ISSUE THREAD

**Issue by ZZHHogan** [chibohe/text_recognition_toolbox#13]
请问SAR如何进行训练呢？
我使用SAR配置文件的时候进行训练，出现这个错误：
![image](https://user-images.githubusercontent.com/40531744/124895262-f9338800-e00e-11eb-88aa-dd4a10a3bd99.png)

初步认为是采用了attention，loss函数不同导致的错误。请问应该怎么解决呢

**Comment by chibohe** [comment]
重新pull一下再试试，我这边测了是没问题的。
