### ISSUE TITLE
请问能识别竖向的文本吗？类似春节对联的那种？

### ISSUE THREAD

**Issue by ZZHHogan** [chibohe/text_recognition_toolbox#5]
您好，我使用了您提供了项目，准确率确实很高，感谢分享！另外想请教一下，能识别竖向的文本吗？就是和春节对联差不多的那种文本？

**Comment by chibohe** [comment]
> 您好，我使用了您提供了项目，准确率确实很高，感谢分享！另外想请教一下，能识别竖向的文本吗？就是和春节对联差不多的那种文本？

可以啊，需要对图片进行一下翻转。代码可以参考dataset.py第236行注释的内容。

**Comment by ZZHHogan** [comment]
> > 您好，我使用了您提供了项目，准确率确实很高，感谢分享！另外想请教一下，能识别竖向的文本吗？就是和春节对联差不多的那种文本？
> 
> 可以啊，需要对图片进行一下翻转。代码可以参考dataset.py第236行注释的内容。

好的谢谢，已经看到，多谢指教
