### ISSUE TITLE
when did you update SATRN tutorial ？ how to train with SATRN

### ISSUE THREAD

**Issue by Johnson-yue** [chibohe/text_recognition_toolbox#6]

**Comment by chibohe** [comment]
> No description provided.

There are some bugs  in the SATRN code, I will update the tutorial until the bugs are fixed.

**Comment by Johnson-yue** [comment]
ok， thank you ，I will test later
I was just getting ready to test it
and found some config is different in paper like num_encoder and num_decoder，

**Comment by chibohe** [comment]
> ok， thank you ，I will test later
> I was just getting ready to test it
> and found some config is different in paper like num_encoder and num_decoder，

Welcome to fix the bugs with me.

**Comment by Johnson-yue** [comment]
> > ok， thank you ，I will test later
> > I was just getting ready to test it
> > and found some config is different in paper like num_encoder and num_decoder，
> 
> Welcome to fix the bugs with me.

I'm happy to do this, but I need to wait until I finish training DAN with your framework, so that I can understand your framework and find the SATRN bug，by the way . what is the bug for now ?

**Comment by ASHU-web** [comment]
is SATRN model working fine now?

**Comment by chibohe** [comment]
> is SATRN model working fine now?

Sorry, I've been busy recently, I will update SATRN asap.
