### ISSUE TITLE
what is the value of 'num_steps '  for predict a new image

### ISSUE THREAD

**Issue by Johnson-yue** [chibohe/text_recognition_toolbox#9]
https://github.com/chibohe/text_recognition_toolbox/blob/5ef1261ec436ee564eb977dcad84ca60b19eaa93/networks/DAN.py#L298

maybe this DAN model have some bug for predict  a new image ？？？

**Comment by chibohe** [comment]
num_steps means the steps in attention decoder. I haven't implemented the inference part for DAN, please try CRNN or SAR model.
